site_name: NJIT Github Enterprise Cloud

nav:
  - Home: index.md
  - 'How To':
    - 'how-to/index.md'
    - 'Get Started': 'how-to/get-started.md'
    - 'Join GEC': 'how-to/invite.md'
    - 'Manage Teams': 'how-to/manage-teams.md'
    - 'Gitlab 2 Github Migration': 'how-to/migrate.md'
theme: 
  name: material
  logo: https://hpc.njit.edu/img/Logo_NJIT.png
  favicon: https://hpc.njit.edu/favicon.ico
  palette:

    # Palette toggle for automatic mode
    #- media: "(prefers-color-scheme)"
    #  toggle:
    #    icon: material/brightness-auto
    #   name: Switch to light mode

    # Palette toggle for light mode
    #- media: "(prefers-color-scheme: light)"
    scheme: njit
     # toggle:
     #   icon: material/toggle-switch
     #   name: Switch to dark mode

    # Palette toggle for dark mode
    #- media: "(prefers-color-scheme: dark)"
    #  scheme: slate
    #  toggle:
    #    icon: material/toggle-switch-off-outline
    #    name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - announce.dismiss
    - content.tooltips
    - header.autohide

extra_css:
    - https://hpc.njit.edu/stylesheets/extra.css
    - stylesheets/extra.css


# Extensions
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

plugins:
  - search
  - markdown-exec
  - table-reader
  - mkdocstrings
  - awesome-pages
  - autolinks
  - macros
#  - blog:
#      blog_dir: news
#      authors: false
#      archive: false

extra:
  social:
    - icon: material/help-box-multiple
      link: https://nexus.njit.edu/highlander_nexus?id=sc_cat_item&sys_id=3f1dd0320a0a0b99000a53f7604a2ef9
      name: Contact IST support
    - icon: fontawesome/solid/paper-plane
      link: mailto:servicedesk@njit.edu
      name: Email IST Service Desk

copyright: Advanced Research Computing Services, New Jersey Institute of Technology
